steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/shiny-farkle', '.']
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['upgrade', '--install', '--set', 'projectId=$PROJECT_ID', 'shiny-farkle', '.']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
  - 'CLOUDSDK_CONTAINER_CLUSTER=shiny-cluster'
images: ['gcr.io/$PROJECT_ID/shiny-farkle:latest']
