---
kind: Template
apiVersion: v1
metadata:
  name: shiny-farkle-template
parameters:
  - name: PROJECT_ID
    required: true
    parameterType: string
  - name: DOMAIN
    required: true
    parameterType: string
objects:
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: shiny-ingress
      annotations:
        kubernetes.io/ingress.global-static-ip-name: shiny-static-ip
    spec:
      rules:
      - host: $(DOMAIN)
        http:
          paths:
          - backend:
              serviceName: shiny-farkle-service
              servicePort: 80
  - apiVersion: v1
    kind: Service
    metadata:
      name: shiny-farkle-service
      labels:
        app: shiny-farkle
    spec:
      type: NodePort
      ports:
      - port: 80
        targetPort: 3838
      selector:
        app: shiny-farkle
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: shiny-farkle-deploy
      labels:
        app: shiny-farkle
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: shiny-farkle
        spec:
          containers:
          - name: master
            imagePullPolicy: Always
            image: gcr.io/$(PROJECT_ID)/shiny-farkle:latest
            ports:
            - containerPort: 3838
